[package]
name = "liquid-assets-deflate"
version = "0.4.0"
edition = "2024"

description = "Compress graphical assets at compile time for embedded targets which can be decompressed on target using liquid-assets-inflate"
homepage = "https://github.com/tom-flaherty/liquid-assets"
repository = "https://github.com/tom-flaherty/liquid-assets"
license = "MIT"
readme = "README.md"
keywords = ["embedded", "graphics", "assets", "pipeline", "compression"]
categories = ["embedded", "no-std"]

[dependencies]
image = "0.25.10"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
strum = "0.28.0"
strum_macros = "0.28.0"

[dev-dependencies]
miniz_oxide = "0.9.1"

