[package]
name = "liquid-assets-inflate"
version = "0.4.0"
edition = "2024"

description = "no-std library for embedded devices to decompress graphical assets compressed with liquid-assets-deflate"
homepage = "https://github.com/tom-flaherty/liquid-assets"
repository = "https://github.com/tom-flaherty/liquid-assets"
license = "MIT"
readme = "README.md"
keywords = ["embedded", "graphics", "assets", "pipeline", "compression"]

[dependencies]
liquid-assets-inflate-macros = { version = "0.4.0" }
